import 'package:injectable/injectable.dart';

import '../../../../core/ai/clinical_ai_service.dart';
import '../../domain/models/ai_health_insight.dart';
import '../../domain/models/bp_trend_point.dart';
import '../../domain/models/care_item.dart';
import '../../domain/models/health_score.dart';
import '../../domain/models/medication_reminder.dart';
import '../../domain/models/patient_profile.dart';
import '../../domain/models/quick_link.dart';
import '../../domain/models/vital_reading.dart';
import '../../domain/repositories/patient_dashboard_repository.dart';
import '../dummy/dummy_patient_dashboard_data.dart';

/// Patient dashboard repository. Non-AI sections use the demo seed; the
/// health insight is generated by [ClinicalAiService].
@LazySingleton(as: PatientDashboardRepository)
class MockPatientDashboardRepository implements PatientDashboardRepository {
  MockPatientDashboardRepository(this._ai);

  final ClinicalAiService _ai;

  static const _simulatedLatency = Duration(milliseconds: 400);

  String? _cachedInsight;

  @override
  Future<PatientProfile> getCurrentPatient() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDashboardData.patient,
    );
  }

  @override
  Future<HealthScore> getHealthScore() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDashboardData.healthScore,
    );
  }

  @override
  Future<List<VitalReading>> getTodayVitals() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDashboardData.todayVitals,
    );
  }

  @override
  Future<List<MedicationReminder>> getMedicationReminders() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDashboardData.medicationReminders,
    );
  }

  @override
  Future<List<CareItem>> getUpcomingCare() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDashboardData.upcomingCare,
    );
  }

  @override
  Future<AiHealthInsight> getAiHealthInsight() async {
    await Future<void>.delayed(_simulatedLatency);
    final message = _cachedInsight ??= await _ai.generatePatientHealthInsight(
      clinicalContext: _patientContext(),
    );
    return AiHealthInsight(
      title: 'Trend Detected',
      tagLabel: 'AI',
      message: message,
      updatedLabel: 'Updated just now',
    );
  }

  @override
  Future<List<QuickLink>> getQuickLinks() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDashboardData.quickLinks,
    );
  }

  @override
  Future<List<BpTrendPoint>> getBpTrend() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDashboardData.bpTrend,
    );
  }

  String _patientContext() {
    final patient = DummyPatientDashboardData.patient;
    final score = DummyPatientDashboardData.healthScore;
    final buffer = StringBuffer()
      ..writeln('Patient: ${patient.fullName} (${patient.displayId})')
      ..writeln(
        'Health score: ${score.score}/${score.maxScore} '
        '(${score.statusLabel}, ${score.trendLabel})',
      )
      ..writeln('Today vitals:');
    for (final vital in DummyPatientDashboardData.todayVitals) {
      buffer.writeln(
        '- ${vital.label}: ${vital.value} ${vital.subLabel} '
        '[${vital.badgeLabel}]',
      );
    }
    buffer.writeln('BP trend:');
    for (final point in DummyPatientDashboardData.bpTrend) {
      buffer.writeln(
        '- ${point.dayLabel}: ${point.systolic}/${point.diastolic}',
      );
    }
    buffer.writeln('Medications:');
    for (final med in DummyPatientDashboardData.medicationReminders) {
      buffer.writeln(
        '- ${med.name}: ${med.detailLine} (${med.status.name})',
      );
    }
    return buffer.toString();
  }
}
