import 'package:injectable/injectable.dart';

import '../../../../core/ai/clinical_ai_service.dart';
import '../../domain/models/ai_health_insight.dart';
import '../../domain/models/bp_trend_point.dart';
import '../../domain/models/care_item.dart';
import '../../domain/models/health_score.dart';
import '../../domain/models/medication_reminder.dart';
import '../../domain/models/patient_profile.dart';
import '../../domain/models/quick_link.dart';
import '../../domain/models/vital_reading.dart';
import '../../domain/repositories/patient_dashboard_repository.dart';
import '../datasources/remote/patient_dashboard_remote_data_source.dart';

/// Every section reads live from Firestore via [PatientDashboardRemoteDataSource];
/// the AI Health Insight is generated by [ClinicalAiService] (Gemini) from
/// that same live context, matching the design's "AI-generated" framing
/// with real data instead of a canned string.
@LazySingleton(as: PatientDashboardRepository)
class PatientDashboardRepositoryImpl implements PatientDashboardRepository {
  final PatientDashboardRemoteDataSource _remoteDataSource;
  final ClinicalAiService _ai;

  PatientDashboardRepositoryImpl(this._remoteDataSource, this._ai);

  String? _cachedInsight;

  @override
  Future<PatientProfile> getCurrentPatient() => _remoteDataSource.readPatient();

  @override
  Future<HealthScore> getHealthScore() => _remoteDataSource.readHealthScore();

  @override
  Future<List<VitalReading>> getTodayVitals() =>
      _remoteDataSource.readTodayVitals();

  @override
  Future<List<MedicationReminder>> getMedicationReminders() =>
      _remoteDataSource.readMedicationReminders();

  @override
  Future<List<CareItem>> getUpcomingCare() =>
      _remoteDataSource.readUpcomingCare();

  @override
  Future<AiHealthInsight> getAiHealthInsight() async {
    final message = _cachedInsight ??= await _ai.generatePatientHealthInsight(
      clinicalContext: await _buildClinicalContext(),
    );
    return AiHealthInsight(
      title: 'Trend Detected',
      tagLabel: 'AI',
      message: message,
      updatedLabel: 'Updated just now',
    );
  }

  @override
  Future<List<QuickLink>> getQuickLinks() => _remoteDataSource.readQuickLinks();

  @override
  Future<List<BpTrendPoint>> getBpTrend() => _remoteDataSource.readBpTrend();

  Future<String> _buildClinicalContext() async {
    final results = await Future.wait([
      _remoteDataSource.readPatient(),
      _remoteDataSource.readHealthScore(),
      _remoteDataSource.readTodayVitals(),
      _remoteDataSource.readMedicationReminders(),
      _remoteDataSource.readBpTrend(),
    ]);
    final patient = results[0] as PatientProfile;
    final score = results[1] as HealthScore;
    final vitals = results[2] as List<VitalReading>;
    final medications = results[3] as List<MedicationReminder>;
    final bpTrend = results[4] as List<BpTrendPoint>;

    final buffer = StringBuffer()
      ..writeln('Patient: ${patient.fullName} (${patient.displayId})')
      ..writeln(
        'Health score: ${score.score}/${score.maxScore} '
        '(${score.statusLabel}, ${score.trendLabel})',
      )
      ..writeln('Today vitals:');
    for (final vital in vitals) {
      buffer.writeln(
        '- ${vital.label}: ${vital.value} ${vital.subLabel} '
        '[${vital.badgeLabel}]',
      );
    }
    buffer.writeln('BP trend:');
    for (final point in bpTrend) {
      buffer.writeln('- ${point.dayLabel}: ${point.systolic}/${point.diastolic}');
    }
    buffer.writeln('Medications:');
    for (final med in medications) {
      buffer.writeln('- ${med.name}: ${med.detailLine} (${med.status.name})');
    }
    return buffer.toString();
  }
}
