// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6XjIuOi4HUebs5wMI9GgWkinTpOks5Xw',
    appId: '1:1043025564694:web:4d95fb2d2cd928d730d137',
    messagingSenderId: '1043025564694',
    projectId: 'ubuzima-connect-alu',
    authDomain: 'ubuzima-connect-alu.firebaseapp.com',
    storageBucket: 'ubuzima-connect-alu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfsq2hhHbiVikRKpqixV2OqmX2KwBhBbo',
    appId: '1:1043025564694:android:b3042cddd436174d30d137',
    messagingSenderId: '1043025564694',
    projectId: 'ubuzima-connect-alu',
    storageBucket: 'ubuzima-connect-alu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClyPe_GkYZ3tokWWwe98LiPmxEUeFb4vI',
    appId: '1:1043025564694:ios:04bbcb1573c5e0f130d137',
    messagingSenderId: '1043025564694',
    projectId: 'ubuzima-connect-alu',
    storageBucket: 'ubuzima-connect-alu.firebasestorage.app',
    iosBundleId: 'com.example.ubuzimaConnect',
  );
}
