import 'package:injectable/injectable.dart';

import '../../../../core/ai/clinical_ai_service.dart';
import '../../domain/models/ai_insight.dart';
import '../../domain/models/allergy.dart';
import '../../domain/models/clinical_note.dart';
import '../../domain/models/clinical_summary_item.dart';
import '../../domain/models/patient_detail.dart';
import '../../domain/models/risk_indicator.dart';
import '../../domain/models/vital_sign.dart';
import '../../domain/repositories/patient_detail_repository.dart';
import '../datasources/remote/patient_detail_remote_data_source.dart';

/// Firestore-backed [PatientDetailRepository]. Chart sections come from
/// [PatientDetailRemoteDataSource]; AI alert and clinical summary are
/// generated by [ClinicalAiService] from that live chart context.
@LazySingleton(as: PatientDetailRepository)
class FirestorePatientDetailRepository implements PatientDetailRepository {
  FirestorePatientDetailRepository(this._remote, this._ai);

  final PatientDetailRemoteDataSource _remote;
  final ClinicalAiService _ai;

  String? _cachedAlert;
  String? _cachedSummary;

  @override
  Future<PatientDetail> getPatientDetail() => _remote.getPatientDetail();

  @override
  Future<RiskProfile> getRiskProfile() => _remote.getRiskProfile();

  @override
  Future<List<VitalSign>> getVitals() => _remote.getVitals();

  @override
  Future<String> getVitalsAsOfLabel() => _remote.getVitalsAsOfLabel();

  @override
  Future<List<Allergy>> getAllergies() => _remote.getAllergies();

  @override
  Future<String> getDrugInteractionMessage() =>
      _remote.getDrugInteractionMessage();

  @override
  Future<List<ClinicalNote>> getClinicalNotes() => _remote.getClinicalNotes();

  @override
  Future<List<ClinicalSummaryItem>> getClinicalSummaryItems() =>
      _remote.getClinicalSummaryItems();

  @override
  Future<String> getAiAlertMessage() async {
    return _cachedAlert ??= await _ai.generatePatientAlert(
      clinicalContext: await _detailContext(),
    );
  }

  @override
  Future<AiInsight> getAiClinicalSummary() async {
    final message = _cachedSummary ??= await _ai.generatePatientClinicalSummary(
      clinicalContext: await _detailContext(),
    );
    return AiInsight(
      title: 'AI Clinical Summary',
      timestampLabel: 'Generated just now',
      message: message,
    );
  }

  Future<String> _detailContext() async {
    final results = await Future.wait([
      getPatientDetail(),
      getVitals(),
      getVitalsAsOfLabel(),
      getAllergies(),
      getDrugInteractionMessage(),
      getRiskProfile(),
      getClinicalNotes(),
    ]);
    final patient = results[0] as PatientDetail;
    final vitals = results[1] as List<VitalSign>;
    final vitalsAsOfLabel = results[2] as String;
    final allergies = results[3] as List<Allergy>;
    final drugInteractionMessage = results[4] as String;
    final riskProfile = results[5] as RiskProfile;
    final notes = results[6] as List<ClinicalNote>;

    final buffer = StringBuffer()
      ..writeln('Patient: ${patient.name}')
      ..writeln('ID: ${patient.patientCode}')
      ..writeln(
        'Demographics: ${patient.gender}, ${patient.age}, DOB '
        '${patient.dateOfBirth}',
      )
      ..writeln('Location: ${patient.location} · ${patient.hospital}')
      ..writeln('Status: ${patient.status.name}')
      ..writeln('Tags: ${patient.tags.join(', ')}')
      ..writeln('Vitals as of: $vitalsAsOfLabel');
    for (final vital in vitals) {
      buffer.writeln(
        '- ${vital.label}: ${vital.value} ${vital.unit}'
        '${vital.status != null ? ' (${vital.status!.name})' : ''}',
      );
    }
    buffer.writeln('Allergies:');
    for (final allergy in allergies) {
      buffer.writeln('- ${allergy.label} (${allergy.severity.name})');
    }
    buffer.writeln('Drug interaction: $drugInteractionMessage');
    buffer.writeln('Overall risk: ${riskProfile.overallLabel}');
    for (final indicator in riskProfile.indicators) {
      buffer.writeln('- ${indicator.label}: ${indicator.percentage}%');
    }
    buffer.writeln('Clinical notes:');
    for (final note in notes.take(5)) {
      buffer.writeln('- ${note.authorName} (${note.timeLabel}): ${note.note}');
    }
    return buffer.toString();
  }
}
