import 'package:injectable/injectable.dart';

import '../../../../core/ai/clinical_ai_service.dart';
import '../../domain/models/ai_insight.dart';
import '../../domain/models/dashboard_stat.dart';
import '../../domain/models/doctor.dart';
import '../../domain/models/emergency_alert.dart';
import '../../domain/models/queue_patient.dart';
import '../../domain/models/referral.dart';
import '../../domain/models/schedule_item.dart';
import '../../domain/repositories/doctor_dashboard_repository.dart';
import '../datasources/remote/doctor_dashboard_remote_data_source.dart';

/// Firestore-backed [DoctorDashboardRepository]. Clinical lists come from
/// [DoctorDashboardRemoteDataSource]; AI copy is generated by
/// [ClinicalAiService] from that live context.
@LazySingleton(as: DoctorDashboardRepository)
class FirestoreDoctorDashboardRepository implements DoctorDashboardRepository {
  FirestoreDoctorDashboardRepository(this._remote, this._ai);

  final DoctorDashboardRemoteDataSource _remote;
  final ClinicalAiService _ai;

  String? _cachedInsight;

  @override
  Future<Doctor> getCurrentDoctor() => _remote.getCurrentDoctor();

  @override
  Future<List<EmergencyAlert>> getEmergencyAlerts() =>
      _remote.getEmergencyAlerts();

  @override
  Future<List<DashboardStat>> getDashboardStats() =>
      _remote.getDashboardStats();

  @override
  Future<List<ScheduleItem>> getTodaySchedule() => _remote.getTodaySchedule();

  @override
  Future<List<QueuePatient>> getPatientQueue() => _remote.getPatientQueue();

  @override
  Future<List<Referral>> getReferrals() => _remote.getReferrals();

  @override
  Future<AiInsight> getAiInsight() async {
    final message = _cachedInsight ??= await _ai.generateDoctorPanelInsight(
      clinicalContext: await _panelContext(),
    );
    return AiInsight(
      title: 'AI Clinical Insight',
      timestampLabel: 'Just now',
      message: message,
    );
  }

  Future<String> _panelContext() async {
    final results = await Future.wait([
      getCurrentDoctor(),
      getEmergencyAlerts(),
      getPatientQueue(),
      getReferrals(),
    ]);
    final doctor = results[0] as Doctor;
    final alerts = results[1] as List<EmergencyAlert>;
    final queue = results[2] as List<QueuePatient>;
    final referrals = results[3] as List<Referral>;

    final buffer = StringBuffer()
      ..writeln('Doctor: ${doctor.fullName}')
      ..writeln('Hospital: ${doctor.hospital}')
      ..writeln('Emergency alerts:');
    for (final alert in alerts) {
      buffer.writeln(
        '- ${alert.patientName} (${alert.severity.name}): ${alert.description}',
      );
    }
    buffer.writeln('Queue:');
    for (final patient in queue) {
      buffer.writeln(
        '- ${patient.name}: ${patient.reason} (${patient.priority.name})',
      );
    }
    buffer.writeln('Referrals:');
    for (final referral in referrals) {
      buffer.writeln(
        '- ${referral.patientName}: ${referral.specialty} '
        '(${referral.status.name})',
      );
    }
    return buffer.toString();
  }
}
