import 'package:injectable/injectable.dart';

import '../../../../core/ai/clinical_ai_service.dart';
import '../../domain/models/ai_insight.dart';
import '../../domain/models/dashboard_stat.dart';
import '../../domain/models/patient_record.dart';
import '../../domain/repositories/patient_search_repository.dart';
import '../datasources/remote/patient_search_remote_data_source.dart';

/// Firestore-backed [PatientSearchRepository]. The patient list/stats come
/// from [PatientSearchRemoteDataSource]; the follow-up AI banner is
/// generated by [ClinicalAiService] from that live panel context.
@LazySingleton(as: PatientSearchRepository)
class FirestorePatientSearchRepository implements PatientSearchRepository {
  FirestorePatientSearchRepository(this._remote, this._ai);

  final PatientSearchRemoteDataSource _remote;
  final ClinicalAiService _ai;

  String? _cachedInsight;

  @override
  Future<List<DashboardStat>> getPatientStats() => _remote.getPatientStats();

  @override
  Future<List<PatientRecord>> getRecentPatients() =>
      _remote.getRecentPatients();

  @override
  Future<AiInsight> getFollowUpInsight() async {
    final message = _cachedInsight ??= await _ai.generateFollowUpInsight(
      clinicalContext: await _searchContext(),
    );
    return AiInsight(
      title: 'AI Alert',
      timestampLabel: 'Just now',
      message: message,
    );
  }

  Future<String> _searchContext() async {
    final patients = await getRecentPatients();
    final buffer = StringBuffer()..writeln('Recent patients:');
    for (final patient in patients) {
      buffer.writeln(
        '- ${patient.name} (${patient.patientCode}): '
        '${patient.tags.join(', ')} · ${patient.status.name} · '
        'last activity ${patient.lastActivityLabel}',
      );
    }
    return buffer.toString();
  }
}
