import 'package:injectable/injectable.dart';

import '../../../../core/ai/clinical_ai_service.dart';
import '../../domain/models/ai_insight.dart';
import '../../domain/models/dashboard_stat.dart';
import '../../domain/models/doctor.dart';
import '../../domain/models/emergency_alert.dart';
import '../../domain/models/queue_patient.dart';
import '../../domain/models/referral.dart';
import '../../domain/models/schedule_item.dart';
import '../../domain/repositories/doctor_dashboard_repository.dart';
import '../dummy/dummy_doctor_dashboard_data.dart';

/// Doctor dashboard repository. Clinical lists still use the demo panel
/// seed; AI copy is generated by [ClinicalAiService] from that live
/// context (not hardcoded marketing text).
@LazySingleton(as: DoctorDashboardRepository)
class MockDoctorDashboardRepository implements DoctorDashboardRepository {
  MockDoctorDashboardRepository(this._ai);

  final ClinicalAiService _ai;

  static const _simulatedLatency = Duration(milliseconds: 400);

  String? _cachedInsight;

  @override
  Future<Doctor> getCurrentDoctor() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyDoctorDashboardData.doctor,
    );
  }

  @override
  Future<List<EmergencyAlert>> getEmergencyAlerts() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyDoctorDashboardData.emergencyAlerts,
    );
  }

  @override
  Future<List<DashboardStat>> getDashboardStats() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyDoctorDashboardData.dashboardStats,
    );
  }

  @override
  Future<List<ScheduleItem>> getTodaySchedule() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyDoctorDashboardData.todaySchedule,
    );
  }

  @override
  Future<List<QueuePatient>> getPatientQueue() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyDoctorDashboardData.patientQueue,
    );
  }

  @override
  Future<List<Referral>> getReferrals() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyDoctorDashboardData.referrals,
    );
  }

  @override
  Future<AiInsight> getAiInsight() async {
    await Future<void>.delayed(_simulatedLatency);
    final message = _cachedInsight ??= await _ai.generateDoctorPanelInsight(
      clinicalContext: _panelContext(),
    );
    return AiInsight(
      title: 'AI Clinical Insight',
      timestampLabel: 'Just now',
      message: message,
    );
  }

  String _panelContext() {
    final buffer = StringBuffer()
      ..writeln('Doctor: ${DummyDoctorDashboardData.doctor.fullName}')
      ..writeln('Hospital: ${DummyDoctorDashboardData.doctor.hospital}')
      ..writeln('Emergency alerts:');
    for (final alert in DummyDoctorDashboardData.emergencyAlerts) {
      buffer.writeln(
        '- ${alert.patientName} (${alert.severity.name}): ${alert.description}',
      );
    }
    buffer.writeln('Queue:');
    for (final patient in DummyDoctorDashboardData.patientQueue) {
      buffer.writeln(
        '- ${patient.name}: ${patient.reason} (${patient.priority.name})',
      );
    }
    buffer.writeln('Referrals:');
    for (final referral in DummyDoctorDashboardData.referrals) {
      buffer.writeln(
        '- ${referral.patientName}: ${referral.specialty} (${referral.status.name})',
      );
    }
    return buffer.toString();
  }
}
