import '../../../../core/ai/clinical_ai_service.dart';
import '../../domain/models/ai_insight.dart';
import '../../domain/models/allergy.dart';
import '../../domain/models/clinical_note.dart';
import '../../domain/models/clinical_summary_item.dart';
import '../../domain/models/patient_detail.dart';
import '../../domain/models/risk_indicator.dart';
import '../../domain/models/vital_sign.dart';
import '../../domain/repositories/patient_detail_repository.dart';
import '../dummy/dummy_patient_detail_data.dart';

/// Patient detail repository fixture for widget tests — the real app now
/// runs on [FirestorePatientDetailRepository]. Chart sections use the demo
/// seed; AI alert and clinical summary are generated by [ClinicalAiService].
class MockPatientDetailRepository implements PatientDetailRepository {
  MockPatientDetailRepository(this._ai);

  final ClinicalAiService _ai;

  static const _simulatedLatency = Duration(milliseconds: 400);

  String? _cachedAlert;
  String? _cachedSummary;

  @override
  Future<PatientDetail> getPatientDetail() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDetailData.patient,
    );
  }

  @override
  Future<RiskProfile> getRiskProfile() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDetailData.riskProfile,
    );
  }

  @override
  Future<String> getAiAlertMessage() async {
    await Future<void>.delayed(_simulatedLatency);
    return _cachedAlert ??= await _ai.generatePatientAlert(
      clinicalContext: _detailContext(),
    );
  }

  @override
  Future<List<VitalSign>> getVitals() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDetailData.vitals,
    );
  }

  @override
  Future<String> getVitalsAsOfLabel() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDetailData.vitalsAsOfLabel,
    );
  }

  @override
  Future<List<Allergy>> getAllergies() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDetailData.allergies,
    );
  }

  @override
  Future<String> getDrugInteractionMessage() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDetailData.drugInteractionMessage,
    );
  }

  @override
  Future<List<ClinicalNote>> getClinicalNotes() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDetailData.clinicalNotes,
    );
  }

  @override
  Future<List<ClinicalSummaryItem>> getClinicalSummaryItems() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientDetailData.clinicalSummaryItems,
    );
  }

  @override
  Future<AiInsight> getAiClinicalSummary() async {
    await Future<void>.delayed(_simulatedLatency);
    final message = _cachedSummary ??= await _ai.generatePatientClinicalSummary(
      clinicalContext: _detailContext(),
    );
    return AiInsight(
      title: 'AI Clinical Summary',
      timestampLabel: 'Generated just now',
      message: message,
    );
  }

  String _detailContext() {
    final patient = DummyPatientDetailData.patient;
    final buffer = StringBuffer()
      ..writeln('Patient: ${patient.name}')
      ..writeln('ID: ${patient.patientCode}')
      ..writeln(
        'Demographics: ${patient.gender}, ${patient.age}, DOB '
        '${patient.dateOfBirth}',
      )
      ..writeln('Location: ${patient.location} · ${patient.hospital}')
      ..writeln('Status: ${patient.status.name}')
      ..writeln('Tags: ${patient.tags.join(', ')}')
      ..writeln('Vitals as of: ${DummyPatientDetailData.vitalsAsOfLabel}');
    for (final vital in DummyPatientDetailData.vitals) {
      buffer.writeln(
        '- ${vital.label}: ${vital.value} ${vital.unit}'
        '${vital.status != null ? ' (${vital.status!.name})' : ''}',
      );
    }
    buffer.writeln('Allergies:');
    for (final allergy in DummyPatientDetailData.allergies) {
      buffer.writeln('- ${allergy.label} (${allergy.severity.name})');
    }
    buffer.writeln(
      'Drug interaction: ${DummyPatientDetailData.drugInteractionMessage}',
    );
    buffer.writeln(
      'Overall risk: ${DummyPatientDetailData.riskProfile.overallLabel}',
    );
    for (final indicator in DummyPatientDetailData.riskProfile.indicators) {
      buffer.writeln('- ${indicator.label}: ${indicator.percentage}%');
    }
    buffer.writeln('Clinical notes:');
    for (final note in DummyPatientDetailData.clinicalNotes.take(5)) {
      buffer.writeln(
        '- ${note.authorName} (${note.timeLabel}): ${note.note}',
      );
    }
    return buffer.toString();
  }
}
