import '../../../../core/ai/clinical_ai_service.dart';
import '../../domain/models/ai_insight.dart';
import '../../domain/models/dashboard_stat.dart';
import '../../domain/models/patient_record.dart';
import '../../domain/repositories/patient_search_repository.dart';
import '../dummy/dummy_patient_search_data.dart';

/// Patient search repository fixture for widget tests — the real app now
/// runs on [FirestorePatientSearchRepository]. List/stats use the demo
/// seed; the follow-up AI banner is generated by [ClinicalAiService].
class MockPatientSearchRepository implements PatientSearchRepository {
  MockPatientSearchRepository(this._ai);

  final ClinicalAiService _ai;

  static const _simulatedLatency = Duration(milliseconds: 400);

  String? _cachedInsight;

  @override
  Future<List<DashboardStat>> getPatientStats() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientSearchData.patientStats,
    );
  }

  @override
  Future<AiInsight> getFollowUpInsight() async {
    await Future<void>.delayed(_simulatedLatency);
    final message = _cachedInsight ??= await _ai.generateFollowUpInsight(
      clinicalContext: _searchContext(),
    );
    return AiInsight(
      title: 'AI Alert',
      timestampLabel: 'Just now',
      message: message,
    );
  }

  @override
  Future<List<PatientRecord>> getRecentPatients() {
    return Future.delayed(
      _simulatedLatency,
      () => DummyPatientSearchData.recentPatients,
    );
  }

  String _searchContext() {
    final buffer = StringBuffer()..writeln('Recent patients:');
    for (final patient in DummyPatientSearchData.recentPatients) {
      buffer.writeln(
        '- ${patient.name} (${patient.patientCode}): '
        '${patient.tags.join(', ')} · ${patient.status.name} · '
        'last activity ${patient.lastActivityLabel}',
      );
    }
    return buffer.toString();
  }
}
