import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:injectable/injectable.dart';

import '../../../../../core/ai/clinical_ai_service.dart';
import '../../../../../core/constants/app_constants.dart';
import '../../../../../core/constants/firestore_paths.dart';
import '../../../../../core/exceptions/app_exceptions.dart';
import '../../../domain/entities/patient_timeline.dart';
import '../../../domain/entities/timeline_event.dart';
import '../local/timeline_local_data_source.dart';

/// Firestore-backed source for DOC-04's timeline. Layout:
///
///   medical_records/{patientId}             → patient header, trend, AI note
///   medical_records/{patientId}/events/{id} → one document per timeline event
///
/// Seeded from [TimelineLocalDataSource] on first read. The AI summary is
/// generated by [ClinicalAiService] when missing or not yet marked generated.
abstract interface class TimelineRemoteDataSource {
  Future<PatientTimeline> readTimeline();
}

@LazySingleton(as: TimelineRemoteDataSource)
class TimelineRemoteDataSourceImpl implements TimelineRemoteDataSource {
  final FirebaseFirestore _firestore;
  final TimelineLocalDataSource _seed;
  final ClinicalAiService _ai;

  TimelineRemoteDataSourceImpl(this._firestore, this._seed, this._ai);

  DocumentReference<Map<String, dynamic>> get _doc => _firestore
      .collection(FirestorePaths.medicalRecords)
      .doc(AppConstants.demoPatientId);

  CollectionReference<Map<String, dynamic>> get _events =>
      _doc.collection('events');

  @override
  Future<PatientTimeline> readTimeline() async {
    try {
      if (!(await _doc.get()).exists) await _seedFirestore();
      final timeline = await _assemble();
      return _ensureAiSummary(timeline);
    } on FirebaseException catch (e) {
      throw ServerException(e.message ?? 'Could not load the timeline.');
    }
  }

  Future<PatientTimeline> _ensureAiSummary(PatientTimeline timeline) async {
    final data = (await _doc.get()).data() ?? const {};
    final alreadyGenerated = data['aiGenerated'] == true;
    final hasSummary = timeline.aiSummary.trim().isNotEmpty;
    if (alreadyGenerated && hasSummary) return timeline;

    final context = StringBuffer()
      ..writeln('Patient: ${timeline.patient.name}')
      ..writeln('Summary: ${timeline.patient.summary}')
      ..writeln('Criticality: ${timeline.patient.criticality}')
      ..writeln('Care history: ${timeline.patient.careHistory}')
      ..writeln('View: ${timeline.aiViewLabel}')
      ..writeln('Trend:');
    for (final point in timeline.trend) {
      context.writeln(
        '- ${point.label}: systolic ${point.systolic}, glucose ${point.glucose}',
      );
    }
    context.writeln('Events:');
    for (final event in timeline.events.take(12)) {
      context.writeln(
        '- ${event.dateLabel}: ${event.title} (${event.category.name}) — '
        '${event.detail}',
      );
    }

    final summary = await _ai.generateTimelineAnalysis(
      clinicalContext: context.toString(),
    );
    await _doc.set({
      'aiSummary': summary,
      'aiGenerated': true,
      'aiGeneratedAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));

    return PatientTimeline(
      patient: timeline.patient,
      trend: timeline.trend,
      events: timeline.events,
      aiSummary: summary,
      totalEvents: timeline.totalEvents,
      earlierCount: timeline.earlierCount,
      aiViewLabel: timeline.aiViewLabel,
    );
  }

  Future<PatientTimeline> _assemble() async {
    final data = (await _doc.get()).data() ?? const {};
    final eventDocs = await _events.orderBy('sortOrder').get();

    return PatientTimeline(
      patient: TimelinePatient(
        name: data['patientName'] as String? ?? '',
        summary: data['patientSummary'] as String? ?? '',
        criticality: data['criticality'] as String? ?? '',
        careHistory: data['careHistory'] as String? ?? '',
      ),
      totalEvents: (data['totalEvents'] as num?)?.toInt() ?? 0,
      earlierCount: (data['earlierCount'] as num?)?.toInt() ?? 0,
      aiViewLabel: data['aiViewLabel'] as String? ?? '',
      aiSummary: data['aiSummary'] as String? ?? '',
      trend: ((data['trend'] as List?) ?? const [])
          .cast<Map<String, dynamic>>()
          .map(
            (t) => TrendPoint(
              label: t['label'] as String? ?? '',
              systolic: (t['systolic'] as num?)?.toDouble() ?? 0,
              glucose: (t['glucose'] as num?)?.toDouble() ?? 0,
            ),
          )
          .toList(),
      events: eventDocs.docs.map((d) => _eventFromMap(d.id, d.data())).toList(),
    );
  }

  TimelineEvent _eventFromMap(String id, Map<String, dynamic> data) {
    return TimelineEvent(
      id: id,
      category: EventCategory.values.byName(
        data['category'] as String? ?? 'visit',
      ),
      title: data['title'] as String? ?? '',
      dateLabel: data['dateLabel'] as String? ?? '',
      year: (data['year'] as num?)?.toInt() ?? 0,
      detail: data['detail'] as String? ?? '',
    );
  }

  Future<void> _seedFirestore() async {
    final timeline = _seed.readTimeline();
    final batch = _firestore.batch();

    batch.set(_doc, {
      'patientName': timeline.patient.name,
      'patientSummary': timeline.patient.summary,
      'criticality': timeline.patient.criticality,
      'careHistory': timeline.patient.careHistory,
      'totalEvents': timeline.totalEvents,
      'earlierCount': timeline.earlierCount,
      'aiViewLabel': timeline.aiViewLabel,
      // Leave blank so Gemini fills it on first read.
      'aiSummary': '',
      'aiGenerated': false,
      'trend': [
        for (final point in timeline.trend)
          {
            'label': point.label,
            'systolic': point.systolic,
            'glucose': point.glucose,
          },
      ],
    });

    for (var i = 0; i < timeline.events.length; i++) {
      final event = timeline.events[i];
      batch.set(_events.doc(event.id), {
        'category': event.category.name,
        'title': event.title,
        'dateLabel': event.dateLabel,
        'year': event.year,
        'detail': event.detail,
        'sortOrder': i,
      });
    }

    await batch.commit();
  }
}
